# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
# 界面文件
from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(850, 260)
        Form.setMinimumSize(QtCore.QSize(850, 260))
        Form.setMaximumSize(QtCore.QSize(850, 260))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 2, 800, 224))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(16, 26, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_input = QtWidgets.QLabel(self.layoutWidget)
        self.label_input.setObjectName("label_input")
        self.horizontalLayout.addWidget(self.label_input)
        self.lineEdit_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.btn_input = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_input.setObjectName("btn_input")
        self.horizontalLayout.addWidget(self.btn_input)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_class = QtWidgets.QLabel(self.layoutWidget)
        self.label_class.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_class.setObjectName("label_class")
        self.horizontalLayout_2.addWidget(self.label_class)
        self.cb_class = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_class.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_class.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cb_class.setObjectName("cb_class")
        self.horizontalLayout_2.addWidget(self.cb_class)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_course = QtWidgets.QLabel(self.layoutWidget)
        self.label_course.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_course.setObjectName("label_course")
        self.horizontalLayout_3.addWidget(self.label_course)
        self.cb_course = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_course.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_course.setObjectName("cb_course")
        self.horizontalLayout_3.addWidget(self.cb_course)
        self.rb_score = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_score.setObjectName("rb_score")
        self.horizontalLayout_3.addWidget(self.rb_score)
        self.rb_rank = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_rank.setObjectName("rb_rank")
        self.horizontalLayout_3.addWidget(self.rb_rank)
        self.btn_plot = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_plot.setObjectName("btn_plot")
        self.horizontalLayout_3.addWidget(self.btn_plot)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_name.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_4.addWidget(self.label_name)
        self.cb_name = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_name.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_name.setObjectName("cb_name")
        self.horizontalLayout_4.addWidget(self.cb_name)
        self.btn_p_plot = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_p_plot.setObjectName("btn_p_plot")
        self.horizontalLayout_4.addWidget(self.btn_p_plot)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "成绩分析App"))
        self.label_input.setText(_translate("Form", "导入excel表格"))
        self.btn_input.setText(_translate("Form", "导入"))
        self.label_class.setText(_translate("Form", "班级"))
        self.label_course.setText(_translate("Form", "学科"))
        self.rb_score.setText(_translate("Form", "成绩"))
        self.rb_rank.setText(_translate("Form", "进步"))
        self.btn_plot.setText(_translate("Form", "生成图表"))
        self.label_name.setText(_translate("Form", "姓名"))
        self.btn_p_plot.setText(_translate("Form", "生成个人分析图表"))

